# Generated by Django 6.0.4 on 2026-04-19 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('inventario', 'Inventario'), ('proveedor', 'Proveedor'), ('analista_reportes', 'Analista Reportes')], default='inventario', max_length=20),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nUsuario',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
